# Dimrail: Clash Config by rokcso
# GitHub: https://github.com/rokcso/dimrail
# Author: https://rokcso.com
# Update: 2026-02-10

# ██████╗  ██╗ ███╗   ███╗ ██████╗   █████╗  ██╗ ██╗
# ██╔══██╗ ██║ ████╗ ████║ ██╔══██╗ ██╔══██╗ ██║ ██║
# ██║  ██║ ██║ ██╔████╔██║ ██████╔╝ ███████║ ██║ ██║
# ██║  ██║ ██║ ██║╚██╔╝██║ ██╔══██╗ ██╔══██║ ██║ ██║
# ██████╔╝ ██║ ██║ ╚═╝ ██║ ██║  ██║ ██║  ██║ ██║ ███████╗
# ╚═════╝  ╚═╝ ╚═╝     ╚═╝ ╚═╝  ╚═╝ ╚═╝  ╚═╝ ╚═╝ ╚══════╝
