# Dimrail: Stash Config by rokcso
# GitHub: https://github.com/rokcso/dimrail
# Author: https://rokcso.com
# Update: 2026-02-10

# â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—  â–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ•—   â–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—   â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—  â–ˆâ–ˆâ•— â–ˆâ–ˆâ•—
# â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•— â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•— â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•— â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•‘
# â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•”â–ˆâ–ˆâ–ˆâ–ˆâ•”â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â• â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•‘
# â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•‘â•šâ–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•— â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•‘
# â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â• â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•‘ â•šâ•â• â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—
# â•šâ•â•â•â•â•â•  â•šâ•â• â•šâ•â•     â•šâ•â• â•šâ•â•  â•šâ•â• â•šâ•â•  â•šâ•â• â•šâ•â• â•šâ•â•â•â•â•â•â•

# è¿è¡Œæ¨¡å¼ï¼šrule/global/direct
mode: rule
# æ—¥å¿—çº§åˆ«ï¼šsilent/info/warning/error/debug
# æ—¥å¿—çº§åˆ«è¶Šé«˜æ—¥å¿—è¾“å‡ºé‡è¶Šå¤§ï¼Œè¶Šå€¾å‘äºè°ƒè¯•ï¼Œè‹¥éœ€è¦è¯·è‡ªè¡Œå¼€å¯
log-level: warning

# DNS é…ç½®
dns:
  # æ˜¯å¦å¼€å¯ IPv6 è§£æ
  ipv6: false
  default-nameserver:
    - 114.114.114.114
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - tls://223.5.5.5:853
    - tls://223.6.6.6:853
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  respect-rules: true
  enhanced-mode: fake-ip # ç¡®ä¿å¯ç”¨Fake IP
  fake-ip-range: 198.18.0.0/16
  # åœ¨ä»¥ä¸‹åˆ—è¡¨çš„åŸŸåå°†ä¸ä¼šè¢«è§£æä¸º fake ipï¼Œè¿™äº›åŸŸåç›¸å…³çš„è§£æè¯·æ±‚å°†ä¼šè¿”å›å®ƒä»¬çœŸå®çš„ IP åœ°å€
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - "+.srv.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.microsoft.com
    - xnotify.xboxmojie.app
    - "+.ipv6.microsoft.com"
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.ff14.sdo.com"
    - ff.dorado.sdo.com
    - "*.mcdn.bilivideo.cn"
    - "+.media.dssott.com"
    - "+.pvp.net"

http:
  url-rewrite:
    - ^https?://(www\.)?(g|google)\.cn https://www.google.com 302

# ä»£ç†æœåŠ¡æä¾›å•†
proxy-providers:
  ProxyProviderA:
    url: https://rokcso.com/ # ç”¨ä½ çš„è®¢é˜…é“¾æ¥æ›¿æ¢
    interval: 10800
    benchmark-url: http://www.gstatic.com/generate_204
    benchmark-timeout: 10
  ProxyProviderB:
    url: https://rokcso.com/ # ç”¨ä½ çš„è®¢é˜…é“¾æ¥æ›¿æ¢
    interval: 10800
    benchmark-url: http://www.gstatic.com/generate_204
    benchmark-timeout: 10

# ä»£ç†ç»„
proxy-groups:
  - name: é»˜è®¤çº¿è·¯
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Proxy.png
    type: select
    proxies:
      - è‡ªåŠ¨é€‰æ‹©
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
      - JP æ—¥æœ¬
      - TW å°æ¹¾
      - US ç¾å›½
      - UK è‹±å›½
      - å…¶ä»–çº¿è·¯
      - DIRECT

  - name: AI Service
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/AI.png
    type: select
    proxies:
      - US ç¾å›½
      - UK è‹±å›½
      - SG æ–°åŠ å¡
      - JP æ—¥æœ¬
      - HK é¦™æ¸¯
      - TW å°æ¹¾
      - å…¶ä»–çº¿è·¯
      - æ‰‹åŠ¨é€‰æ‹©

  - name: Apple
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Apple.png
    type: select
    proxies:
      - HK é¦™æ¸¯
      - US ç¾å›½
      - SG æ–°åŠ å¡
      - JP æ—¥æœ¬
      - TW å°æ¹¾
      - UK è‹±å›½
      - å…¶ä»–çº¿è·¯
      - æ‰‹åŠ¨é€‰æ‹©

  - name: Telegram
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Telegram.png
    type: select
    proxies:
      - SG æ–°åŠ å¡
      - HK é¦™æ¸¯
      - JP æ—¥æœ¬
      - TW å°æ¹¾
      - US ç¾å›½
      - UK è‹±å›½
      - å…¶ä»–çº¿è·¯
      - æ‰‹åŠ¨é€‰æ‹©

  - name: Spotify
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Spotify.png
    type: select
    proxies:
      - æµåª’ä½“ä¸“ç”¨
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
      - US ç¾å›½
      - JP æ—¥æœ¬
      - TW å°æ¹¾
      - UK è‹±å›½
      - å…¶ä»–çº¿è·¯
      - æ‰‹åŠ¨é€‰æ‹©

  - name: YouTube
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/YouTube.png
    type: select
    proxies:
      - æµåª’ä½“ä¸“ç”¨
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
      - TW å°æ¹¾
      - JP æ—¥æœ¬
      - US ç¾å›½
      - UK è‹±å›½
      - å…¶ä»–çº¿è·¯
      - æ‰‹åŠ¨é€‰æ‹©

  - name: GitHub
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/GitHub.png
    type: select
    proxies:
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
      - JP æ—¥æœ¬
      - TW å°æ¹¾
      - US ç¾å›½
      - UK è‹±å›½
      - å…¶ä»–çº¿è·¯
      - æ‰‹åŠ¨é€‰æ‹©
      - DIRECT

  - name: Web3
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Cryptocurrency.png
    type: select
    proxies:
      - US ç¾å›½
      - SG æ–°åŠ å¡
      - HK é¦™æ¸¯
      - JP æ—¥æœ¬
      - UK è‹±å›½
      - TW å°æ¹¾
      - å…¶ä»–çº¿è·¯
      - æ‰‹åŠ¨é€‰æ‹©
      - DIRECT

  # åŸºäºåœ°åŒºåˆ†ç»„
  - name: HK é¦™æ¸¯
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Hong_Kong.png
    type: select
    include-all: true
    filter: "(?i)(æ¾³é—¨|ğŸ‡²ğŸ‡´|Macau|Macao|é¦™æ¸¯|ğŸ‡­ğŸ‡°|Hong Kong|HK|HKG)"
    proxies:
      - HK-Auto
  - name: HK-Auto
    hidden: true
    type: url-test
    interval: 300
    timeout: 5
    lazy: true
    tolerance: 100
    include-all: true
    filter: "(?i)(æ¾³é—¨|ğŸ‡²ğŸ‡´|Macau|Macao|é¦™æ¸¯|ğŸ‡­ğŸ‡°|Hong Kong|HK|HKG)"

  - name: SG æ–°åŠ å¡
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Singapore.png
    type: select
    include-all: true
    filter: "æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|SG|(?i)Singapore"
    proxies:
      - SG-Auto
  - name: SG-Auto
    hidden: true
    type: url-test
    interval: 300
    timeout: 5
    lazy: true
    tolerance: 100
    include-all: true
    filter: "æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|SG|(?i)Singapore"

  - name: JP æ—¥æœ¬
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Japan.png
    type: select
    include-all: true
    filter: "(?i)(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|ä¸œäº¬|å¤§é˜ª|JP|Japan|Tokyo|Osaka)"
    proxies:
      - JP-Auto
  - name: JP-Auto
    hidden: true
    type: url-test
    interval: 300
    timeout: 5
    lazy: true
    tolerance: 100
    include-all: true
    filter: "(?i)(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|ä¸œäº¬|å¤§é˜ª|JP|Japan|Tokyo|Osaka)"

  - name: TW å°æ¹¾
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Taiwan.png
    type: select
    include-all: true
    filter: "(?i)(å°æ¹¾|ğŸ‡¹ğŸ‡¼|TW|Taiwan|å°-|å°_|Taipei|TPE)"
    proxies:
      - TW-Auto
  - name: TW-Auto
    hidden: true
    type: url-test
    interval: 300
    timeout: 5
    lazy: true
    tolerance: 100
    include-all: true
    filter: "(?i)(å°æ¹¾|ğŸ‡¹ğŸ‡¼|TW|Taiwan|å°-|å°_|Taipei|TPE)"

  - name: US ç¾å›½
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/United_States.png
    type: select
    include-all: true
    filter: "(?i)(ç¾å›½|ğŸ‡ºğŸ‡¸|US|USA|United States|America|Los Angeles|New York|San Francisco|Seattle|Chicago|ç¾è¥¿|ç¾ä¸œ|è¥¿éƒ¨|ä¸œéƒ¨)"
    proxies:
      - US-Auto
  - name: US-Auto
    hidden: true
    type: url-test
    interval: 300
    timeout: 5
    lazy: true
    tolerance: 100
    include-all: true
    filter: "(?i)(ç¾å›½|ğŸ‡ºğŸ‡¸|US|USA|United States|America|Los Angeles|New York|San Francisco|Seattle|Chicago|ç¾è¥¿|ç¾ä¸œ|è¥¿éƒ¨|ä¸œéƒ¨)"

  - name: UK è‹±å›½
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/United_Kingdom.png
    type: select
    include-all: true
    filter: "(?i)(è‹±å›½|ğŸ‡¬ğŸ‡§|UK|United Kingdom|Britain|ä¼¦æ•¦|London|Manchester|Birmingham)"
    proxies:
      - UK-Auto
  - name: UK-Auto
    hidden: true
    type: url-test
    interval: 300
    timeout: 5
    lazy: true
    tolerance: 100
    include-all: true
    filter: "(?i)(è‹±å›½|ğŸ‡¬ğŸ‡§|UK|United Kingdom|Britain|ä¼¦æ•¦|London|Manchester|Birmingham)"

  - name: æµåª’ä½“ä¸“ç”¨
    hidden: true
    type: url-test
    interval: 300
    timeout: 5
    lazy: true
    tolerance: 100
    include-all: true
    filter: "(?i)(IPLC|IEPL|ä¸“çº¿|æ¸¸æˆ|Game|Media|æµåª’ä½“|Netflix|Disney|HBO|Prime|Video|NF|åŸç”Ÿ|Native|è§£é”|Unlock|Premium|Elite|Pro)"

  - name: å…¶ä»–çº¿è·¯
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/World_Map.png
    type: select
    include-all: true
    filter: "(?i)^(?!.*(?:ğŸ‡­ğŸ‡°|é¦™æ¸¯|HK|Hong Kong|ğŸ‡¹ğŸ‡¼|å°æ¹¾|è‡ºç£|TW|Taiwan|ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|JP|Japan|ğŸ‡°ğŸ‡·|éŸ©å›½|KR|Korea|ğŸ‡ºğŸ‡¸|ç¾å›½|US|USA|America|ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|SG|Singapore|ğŸ‡¨ğŸ‡³|ä¸­å›½|CN|China|ğŸ‡¬ğŸ‡§|è‹±å›½|UK|Britain|London|\\.com\\b|ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|(?:\\b(?:USE|USED|TOTAL|Traffic|Expire|EMAIL|Panel|Channel|Author)\\b)|(?:\\d{4}-\\d{2}-\\d{2}|\\d+G))).*$"
    proxies:
      - å…¶ä»–-Auto
  - name: å…¶ä»–-Auto
    hidden: true
    type: url-test
    interval: 300
    timeout: 5
    lazy: true
    tolerance: 100
    include-all: true
    filter: "(?i)^(?!.*(?:ğŸ‡­ğŸ‡°|é¦™æ¸¯|HK|Hong Kong|ğŸ‡¹ğŸ‡¼|å°æ¹¾|è‡ºç£|TW|Taiwan|ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|JP|Japan|ğŸ‡°ğŸ‡·|éŸ©å›½|KR|Korea|ğŸ‡ºğŸ‡¸|ç¾å›½|US|USA|America|ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|SG|Singapore|ğŸ‡¨ğŸ‡³|ä¸­å›½|CN|China|ğŸ‡¬ğŸ‡§|è‹±å›½|UK|Britain|London|\\.com\\b|ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|(?:\\b(?:USE|USED|TOTAL|Traffic|Expire|EMAIL|Panel|Channel|Author)\\b)|(?:\\d{4}-\\d{2}-\\d{2}|\\d+G))).*$"

  # ä¸é™åˆ¶åœ°åŒº
  - name: è‡ªåŠ¨é€‰æ‹©
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Auto.png
    type: url-test
    interval: 300
    timeout: 5
    lazy: true
    tolerance: 100
    include-all: true
    filter: "^(?!.*(?:ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|\\.com\\b|(?:\\b(?:USE|USED|TOTAL|Traffic|Expire|EMAIL|Panel|Channel|Author)\\b)|(?:\\d{4}-\\d{2}-\\d{2}|\\d+G))).*$"

  - name: æ‰‹åŠ¨é€‰æ‹©
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Static.png
    type: select
    include-all: true
    filter: "^(?!.*(?:ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|\\.com\\b|(?:\\b(?:USE|USED|TOTAL|Traffic|Expire|EMAIL|Panel|Channel|Author)\\b)|(?:\\d{4}-\\d{2}-\\d{2}|\\d+G))).*$"

# è§„åˆ™æä¾›å•†
rule-providers:
  lancidr:
    type: http
    behavior: ipcidr
    format: yaml
    url: https://raw.githubusercontent.com/rokcso/dimrail/refs/heads/main/rules/lancidr.yaml
    path: ./rules/lancidr.yaml
    interval: 604800
  reject:
    type: http
    behavior: domain
    format: yaml
    url: https://anti-ad.net/clash.yaml
    path: ./rules/reject.yaml
    interval: 86400
  ai-offshore:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/rokcso/dimrail/refs/heads/main/rules/ai-offshore.yaml
    path: ./rules/ai-offshore.yaml
    interval: 604800
  apple-offshore:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/rokcso/dimrail/refs/heads/main/rules/apple-offshore.yaml
    path: ./rules/apple-offshore.yaml
    interval: 604800
  apple-cn:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/rokcso/dimrail/refs/heads/main/rules/apple-cn.yaml
    path: ./rules/apple-cn.yaml
    interval: 604800
  github:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/rokcso/dimrail/refs/heads/main/rules/github.yaml
    path: ./rules/github.yaml
    interval: 604800
  web3:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/rokcso/dimrail/refs/heads/main/rules/web3.yaml
    path: ./rules/web3.yaml
    interval: 604800
  telegram:
    type: http
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/telegram.list
    interval: 86400
  spotify:
    type: http
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/spotify.list
    interval: 86400
  youtube:
    type: http
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/youtube.list
    interval: 86400

# è§„åˆ™é…ç½®
rules:
  - RULE-SET,lancidr,DIRECT
  - GEOSITE,cn,DIRECT
  - GEOIP,CN,DIRECT
  - DOMAIN-SUFFIX,ahrefs.com,é»˜è®¤çº¿è·¯
  - DOMAIN-SUFFIX,appsflyer.com,é»˜è®¤çº¿è·¯
  # - RULE-SET,reject,REJECT
  - DOMAIN-SUFFIX,larksuite.com,DIRECT
  - RULE-SET,ai-offshore,AI Service
  - RULE-SET,apple-cn,DIRECT
  - RULE-SET,apple-offshore,Apple
  - RULE-SET,github,GitHub
  - RULE-SET,web3,Web3
  - RULE-SET,telegram,Telegram
  - RULE-SET,spotify,Spotify
  - RULE-SET,youtube,YouTube
  - MATCH,é»˜è®¤çº¿è·¯
